using CLDV6211_POE_PART1.Data;
using CLDV6211_POE_PART1.Models;
using CLDV6211_POE_PART1.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace CLDV6211_POE_PART1.Controllers
{
    /*This class was auto created/generated by the IDE*/
    public class HomeController : Controller
    {
        private readonly CLDV6211_DbContext _context;

        public HomeController(CLDV6211_DbContext context)
        {
            _context = context;
        }

        // This action method retrieves data from the database and passes it to the view for display.
        // It uses asynchronous programming to ensure that the application remains responsive while fetching data.
        public async Task<IActionResult> Index()
        {
            var model = new HomeIndexViewModel
            {
                Venues = await _context.Venues.ToListAsync(),
                Events = await _context.Events.Include(e => e.Venue).ToListAsync(),
                Bookings = await _context.Bookings.Include(b => b.Event).ThenInclude(e => e.Venue).ToListAsync()
            };

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        // This action method handles errors and returns an error view with relevant information about the request.
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}